VL Notes on Python Basics

# Class 01

## Data types

In [30]:
pi = 3.14
food = 'pizza'
colors = ['red', 'blue', 'yellow']
user_profile = {'email': 'buffy@gmail.com', 'age': 19, 'password': 'hunter2', 'profession': 'Vampire Slayer' }
shapes = ('square', 'round', 'hexagonic')
age = 25
age_valid = (age < 18)
print("Variables are now defined!")

Variables are now defined!


In [31]:
# $DELETE_BEGIN
pi_type = float
food_type = str
colors_type = list
user_profile_type = dict
shapes_type = tuple
age_valid_type = bool
# $DELETE_END

In [33]:
type(pi) == pi_type \
and type(food) == food_type \
and type(colors) == colors_type \
and type(shapes) == shapes_type \
and type(user_profile) == user_profile_type \
and type(age_valid) == age_valid_type

True

## Functions

### Currencies convertor

In [35]:
# Criando um dicionario com algumas moedas
rates = {
    "USDEUR": 0.85,
    "GBPEUR": 1.13,
    "CHFEUR": 0.86,
    "EURGBP": 0.885
}

In [36]:
def convert(amount, currency):
    """ returns the converted amount in the given currency
    amount is a tuple like (100, "EUR")
    currency is a string"""
    for key, value in rates.items():
        if amount[1] == key[0:3] and currency == "EUR":
            return round(value * amount[0])
        if amount[1] == key[3:6] and currency == key[0:3]:
            return round(amount[0]/value)
    
    

In [37]:
## Testing the function

In [38]:
amount = (100, "USD")
result = convert(amount, "EUR")
result

85

In [39]:
amount = (200, "CHF")
result_2 = convert(amount, "EUR")
result_2

172

### Sum of three

In [84]:
def sum3(numA, numB, numC):
    """
    Takes three numbers and returns the sum of those numbers
    """
    # YOUR CODE HERE
    return float(numA) + float(numB) + float(numC)

In [85]:
sum3(1, 3, 5)

9.0

## Working with strings

### Defining few funstions:

In [88]:
def add_comma(a_string):
    """
    returns a copy of the string with every word separated by a comma
    example: add_comma("John Peter Jude") => "John, Peter, Jude"
    """
    return a_string.replace(" ", ", ")

In [89]:
add_comma("John Peter Jude")

'John, Peter, Jude'

In [90]:
def belongs_to(a_string, a_word):
    """
    returns True if a_string contains a_word
    example: belongs_to("hey jude", "jude") => True
    """
    return a_word in a_string

In [91]:
belongs_to("hey jude", "jude")

True

In [92]:
def count_repetition(a_string, a_substring):
    """
    returns how many times a_substring occurs in a_string
    example: count_repetition("000123000123", "0") => 6
    """
    return a_string.count(a_substring)


In [93]:
count_repetition("000123000123", "0")

6

In [94]:
def is_a_question(a_string):
    """
    returns True if a_string ends with a "?"
    example: is_a_question("How are you?") => True
    """
    return a_string[-1] == "?"

In [95]:
is_a_question("How are you?")

True

In [98]:
def remove_surrounding_whitespaces(a_string):
    """
    returns a copy of the string with leading and trailing whitespaces removed
    example: delete_surrounding_whitespaces("  hey yo  ") => "hey yo"
    """
    return a_string.strip()

In [100]:
remove_surrounding_whitespaces("  hey yo  ")

'hey yo'

In [101]:
def replace(initial_string, old_letter, new_letter):
    """
    returns a copy of the string with the new letter replacing the old one
    example: replace("casanova", "a", "o") => "cosonovo"
    """
    return initial_string.replace(old_letter,new_letter)

In [102]:
replace("casanova", "a", "o")

'cosonovo'

In [105]:
def full_description_concatenation(first_name, last_name, age):
    """
    returns a sentence with the first_name and the last_name capitalized and
     the age using concatenation
    example: full_description_concatenation("john", "doe", 33) => "John Doe is 33"
    """
    return f"{first_name.capitalize()} {last_name.capitalize()} is {age}"

In [106]:
full_description_concatenation("john", "doe", 33)

'John Doe is 33'

## Credit card fundtion

Create a fuction credit_card_industry which takes one parameter (a str storing a credit card number like "4242 4242 4242 4242" for instance) and return one of the following industries:

Airline
Visa
Mastercard
Other

In [47]:
def credit_card_industry(Credit_card):
    first_digit = int(Credit_card[0])
    if first_digit == 1:
        return "Airline"
    elif first_digit == 2:
        return "Mastercard"
    elif first_digit == 3:
        return "American Express"
    elif first_digit == 4:
        return "Visa"
    elif first_digit == 5:
        return "Mastercard"
    else:
        return "Other"
        

In [48]:
credit_card_industry("4242 4242 4242 4242")

'Visa'

Automating the function of credit card

In [56]:
def credit_card_industry(Credit_card):
    mapping = {
        "1": "Airline",
        "2": "Mastercard",
        "4": "Visa",
        "5": "Mastercard"
    }
    return mapping.get(Credit_card[0], "Other")

In [57]:
credit_card_industry("4242 4242 4242 4242")

'Visa'

## Lists

In [58]:
genres = [ 'drama', 'thriler', 'action' ]
print(genres)

['drama', 'thriler', 'action']


In [59]:
genres.append('comedy')
print(genres)

['drama', 'thriler', 'action', 'comedy']


In [60]:
for index, genre in enumerate(sorted(genres)):
    print (f'{index +1} - {genre.capitalize()}')

1 - Action
2 - Comedy
3 - Drama
4 - Thriler


## Dictionaries

In [62]:
movie = {
    'year': 1972,
    'title': 'The Godfather'
}
print(movie)

{'year': 1972, 'title': 'The Godfather'}


In [65]:
# Add a director:
movie["director"] = "Francis Ford Coppola"
print (movie)

{'year': 1972, 'title': 'The Godfather', 'director': 'Francis Ford Coppola'}


In [68]:
movies = []

#Add the movie above
movies.append(movie)

# Add new movies to the list:
movies.append({ 'title': 'The Dark Knight', 'year': 2008, 'director': 'Christopher Nolan' })
movies.append({ 'title': 'The Matrix ', 'year': 1999, 'director': 'The Wachowski Brothers' })

movies

[{'year': 1972, 'title': 'The Godfather', 'director': 'Francis Ford Coppola'},
 {'title': 'The Dark Knight', 'year': 2008, 'director': 'Christopher Nolan'},
 {'title': 'The Matrix ', 'year': 1999, 'director': 'The Wachowski Brothers'}]

In [73]:
# Print movies {name} + {director} + {year}

for movie in movies:
    print (f"""{movie['title']} by {movie['director']} was released in {movie['year']}""")
    
    
    

The Godfather by Francis Ford Coppola was released in 1972
The Dark Knight by Christopher Nolan was released in 2008
The Matrix  by The Wachowski Brothers was released in 1999


## Dictionaries plus Lists

In [74]:
# Getting to know the items in the dictionary

movie = {
    'title': { 'en': 'The Dark Knight', 'fr': 'Le Chevalier Noir' },
    'year': 2008,
    'director': 'Christopher Nolan',
    'rating': 'PG-13',
    'plot': {
        'en': 'The Batman is out for blood',
        'fr': 'Batman est de retour, plus vénère que jamais'
    },
    'box office USD': {'USA': 535_234_033, 'rest_of_world': 469_700_000 },
    'actors': {
        'lead': ['Christian Bale', 'Heath Ledger'],
        'support': ['Aaron Eckhardt', 'Morgan Freeman', 'Gary Oldman', 'Maggie Gyllenhaal' ]
    }
}
print("movie is defined!")


movie is defined!


In [75]:
movie['title']['fr']

'Le Chevalier Noir'

In [76]:
movie['plot']['fr']

'Batman est de retour, plus vénère que jamais'

In [80]:
# Extract 1 list with all the actors

# If we select only movies we have a dictionary not a list!!!
movie['actors']

{'lead': ['Christian Bale', 'Heath Ledger'],
 'support': ['Aaron Eckhardt',
  'Morgan Freeman',
  'Gary Oldman',
  'Maggie Gyllenhaal']}

In [81]:
# in order to get the list of actors, we need to go 1 step further

movie['actors']['lead']+movie['actors']['support']


['Christian Bale',
 'Heath Ledger',
 'Aaron Eckhardt',
 'Morgan Freeman',
 'Gary Oldman',
 'Maggie Gyllenhaal']

# Data Sourcing

## CSV

In [112]:
!pwd

/Users/vanessalieberg/code/Megeve2022/data-challenges/01-Python


In [113]:
import csv

# First version
with open('02-Data-Sourcing/01-CSV/data/phone_book.csv', mode='r') as csv_file:
    csv_reader = csv.reader(csv_file)
    line_count = 0
    for row in csv_reader:
        if line_count > 0:
            print(f"{row[1]}: {row[2]}")
        line_count += 1

print("---")

Lennon: 123
Harrisson: 456
Starr: 789
---


In [117]:
# Importing as dictionary

with open("02-Data-Sourcing/01-CSV/data/phone_book.csv", mode="r") as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        print (f"{row['last_name']}: {row['phone_number']}")


Lennon: 123
Harrisson: 456
Starr: 789


# Matrix

Matrix using numpy as np

In [124]:
import numpy as np
import pandas as pd

a1 = np.arange(24)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [128]:
# Tranforming the matrix a1 into a pandas DataFrame for better viewing
matrix_df = pd.DataFrame(a1)
matrix_df

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
20  20
21  21
22  22
23  23

In [120]:
a1.shape

(24,)

In [122]:
a1.ndim

1

In [123]:
a1[0]

0

In [129]:
# Reshape a matrix
a1.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [131]:
matrix_df_reshaped = pd.DataFrame(a1.reshape(1,24))
matrix_df_reshaped

0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0   0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   

   21  22  23  
0  21  22  23  

[1 rows x 24 columns]

In [134]:
# Matrix changes its dimension to 2!
matrix_df_reshaped.ndim

2

In [135]:
# Looking for a value inside the new matrix
a1.reshape(1,24)[0,3]

3

In [143]:
# Looking into the pandas table
matrix_df_reshaped[3][0]

3

In [147]:
a1.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [145]:
matrix_df_3 = pd.DataFrame(a1.reshape(24,1))
matrix_df_3

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
20  20
21  21
22  22
23  23